./compile.sh adpcm 
./compile.sh bubblesort25
./compile.sh cdaudio
./compile.sh cnt
./compile.sh cntShortest
./compile.sh compress
./compile.sh diskperf
./compile.sh expint
./compile.sh floppy
./compile.sh floppy2
./compile.sh fly_by_wire
./compile.sh insertsort25
./compile.sh kbfiltr
./compile.sh kbfiltr2
./compile.sh pals2
./compile.sh pals3
./compile.sh pals4
./compile.sh pals5
./compile.sh pals6
./compile.sh pals7
./compile.sh pals8
./compile.sh pals9
./compile.sh pals14
./compile.sh pals15
./compile.sh pals16
./compile.sh pals17-LARGE
./compile.sh pals17-SMALL
./compile.sh pals18
./compile.sh pals19
./compile.sh pals20
./compile.sh pals21
./compile.sh pals22-LARGE
./compile.sh pals22-SMALL
./compile.sh pals23
./compile.sh problem10
./compile.sh problem11
./compile.sh statemate
./compile.sh statemate2
./compile.sh sumsubset
./compile.sh tcas
./compile.sh test
./compile.sh test1
./compile.sh test2
./compile.sh test3
./compile.sh test4
./compile.sh test5
./compile.sh test6
./compile.sh test7
./compile.sh test8
./compile.sh test9
./compile.sh test10
./compile.sh test13
./compile.sh test14
./compile.sh test18-LARGE
./compile.sh test18-SMALL
./compile.sh test19-LARGE
./compile.sh test19-SMALL
./compile.sh test20-LARGE
./compile.sh test20-SMALL
./compile.sh test21
./compile.sh test25
./compile.sh test26
./compile.sh test29
./compile.sh test30
./compile.sh test31
./compile.sh test32
./compile.sh test33
./compile.sh test34
./compile.sh test35
./compile.sh test36
./compile.sh test37
./compile.sh test38
./compile.sh test45
./compile.sh test45-SMALL
./compile.sh test46
./compile.sh test46-SMALL
./compile.sh test47
./compile.sh test47-SMALL
./compile.sh test49
./compile.sh test49-SMALL
./compile.sh test50
./compile.sh test50-SMALL
./compile.sh test81
./compile.sh test81-SMALL
./compile.sh test82
./compile.sh test82-SMALL
./compile.sh test84
./compile.sh test84-SMALL
./compile.sh test85
./compile.sh test85-SMALL
